services:
  web:
    image: ums_web
    build:
      context: ./web
      dockerfile: Dockerfile
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: mysql_container
    ports:
      - 8080:8080
    networks:
      - ums_network
    depends_on:
      mysql:
        condition: service_healthy
  export:
    image: ums_export
    build:
      context: ./export
      dockerfile: DockerFile
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: mysql_container
    ports:
      - 8081:8081
    volumes:
      - export-data:/export
    networks:
      - ums_network
    depends_on:
      mysql:
        condition: service_healthy
  import:
    image: ums_import
    build:
      context: ./import
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: mysql_container
    networks:
      - ums_network
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql_container
    environment:
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ums_db
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - ums_network
    healthcheck:
      test: ["CMD","mysqladmin","ping","--silent"]
      interval: 30s
      retries: 3
      timeout: 15s
volumes:
  mysql-data:
  export-data:
networks:
  ums_network: